# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-30 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190527_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=256)),
                ('mail', models.CharField(max_length=64)),
                ('is_delete', models.BooleanField(default=False)),
                ('icon', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'axf_user',
            },
        ),
    ]
