# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-01 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190601_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='icon',
            field=models.ImageField(upload_to='static/media'),
        ),
    ]
