# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-01 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190601_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=64)),
                ('gnum', models.IntegerField(default=1)),
                ('is_select', models.BooleanField(default=False)),
            ],
        ),
    ]
