# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-02 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_cartmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='goodid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Goods'),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.UserModel'),
        ),
    ]
