# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-08 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=18, max_length=8),
        ),
    ]
