# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-22 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_num', models.IntegerField(default=1)),
                ('is_selected', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderGoodModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('og_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_num', models.CharField(max_length=128)),
                ('o_time', models.DateTimeField(auto_now=True)),
                ('o_stau', models.IntegerField(default=1)),
                ('o_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserModel')),
            ],
        ),
        migrations.AlterField(
            model_name='good',
            name='categoryid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='good',
            name='childcid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='good',
            name='isxf',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='good',
            name='pmdesc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='good',
            name='productnum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='good',
            name='storenums',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='ordergoodmodel',
            name='og_good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Good'),
        ),
        migrations.AddField(
            model_name='ordergoodmodel',
            name='og_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.OrderModel'),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='c_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Good'),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='c_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserModel'),
        ),
    ]
