# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-10 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('sex', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='cid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.People'),
        ),
    ]
