# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-02 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('userImg', models.ImageField(upload_to='static/media')),
            ],
            options={
                'db_table': 'axf_user',
            },
        ),
    ]
