# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-03 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=64)),
                ('gnum', models.IntegerField(default=1)),
                ('is_select', models.BooleanField(default=False)),
                ('goodid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Goods')),
                ('userid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
    ]
